### ISSUE TITLE
add project info to modal popup

### ISSUE THREAD

**Issue by techieshark** [climateaction-tech/site#4]
When you click on one of the projects listed on the front page, a modal pops up with some filler content. 

We should fill that in.

Example:

![Screenshot of modal, showing dummy content](https://user-images.githubusercontent.com/1072292/29061173-992cf504-7bd1-11e7-8031-281106b6f3e4.png)

**Comment by techieshark** [comment]
Going to 🛌, hope to get this tomorrow.

**Comment by techieshark** [comment]
@climatesam the map we're referencing is the one from the site organizing for the climate march, right? https://techsector.peoplesclimate.org/

That site says "This was designed and created by members of the Climate Tech group."  Can you or Andy tell me more about what we did on that? (Or do you just want to write the copy for this project?) I figure we'll link to techsector.peoplesclimate.org but I'm not sure what the rest of the copy should say.

**Comment by climatesam** [comment]
I'll update it.

**Comment by techieshark** [comment]
This has been fixed.
